// Re-export the shared validation contract so components import from the feature.
export {
  installSkillSchema,
  updateInstalledSkillSchema,
  assignSkillSchema,
  executeToolSchema,
  configureSkillSchema,
  connectSkillSchema,
} from '@vaep/types';
export type {
  SkillCategory,
  SkillConnectionType,
  SkillConnectionStatus,
  SkillConnectionDto,
  SkillDefinitionDto,
  ConfigFieldDto,
  ConfigFieldType,
  ToolDefinitionDto,
  ToolParametersDto,
  InstalledSkillDto,
  ConnectorHealthDto,
  EmployeeSkillDto,
  ToolCallDto,
  SkillExecutionDto,
  SkillExecutionStatus,
  InstallSkillDto,
  UpdateInstalledSkillDto,
  AssignSkillDto,
  ExecuteToolDto,
  ConfigureSkillDto,
  ConnectSkillDto,
  OAuthAuthorizeDto,
} from '@vaep/types';
